// <auto-generated />
namespace GestionUsuarios.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class store_email : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(store_email));
        
        string IMigrationMetadata.Id
        {
            get { return "201903310447579_store_email"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
