// <auto-generated />
namespace GestionUsuarios.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class columnasdecontroldeacceso : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(columnasdecontroldeacceso));
        
        string IMigrationMetadata.Id
        {
            get { return "201904271622148_columnas-de-control-de-acceso"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
